### ISSUE TITLE
在ex3的oneVsAll中的@（t）是什么意思？

### ISSUE THREAD

**Issue by UesugiErii** [lawlite19/MachineLearningEx#1]
下面这一行中            @(t)(lrCostFunction      我无法理解
	[all_theta(c,:)] = fmincg (@(t)(lrCostFunction(t, X, (y == c), lambda)), initial_theta, options);

能给个详细的解释吗？

**Comment by lawlite19** [comment]
@是函数句柄，t相当于因变量，fmincg 会最小化代价函数，初始值是initial_theta，因为theta是需要迭代计算的（这里就是t），所以每次迭代需要将梯度下降后的theata再传入代价函数计算，所以是@(t).我的理解。

**Comment by lawlite19** [comment]
另外右上角欢迎给个star，fork 👍
